substitutions:
  _SERVICE: agents-portal
  _TAG: manual
  _REGION: us-west1
  _API_URL: https://api.pivota.cc
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=NEXT_PUBLIC_API_URL=${_API_URL}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE}:${_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE}:latest
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE}:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE}:latest
options:
  machineType: E2_HIGHCPU_8
timeout: 1800s
